"""initial schema

Revision ID: 9518455a983e
Revises: 
Create Date: 2026-06-27 18:02:27.025472
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9518455a983e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes_cache',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('secrets',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('ciphertext', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('symbols',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('display_symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.create_index('ix_symbols_display_exchange', ['display_symbol', 'exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_symbols_display_symbol'), ['display_symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_symbols_exchange'), ['exchange'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symbols_exchange'))
        batch_op.drop_index(batch_op.f('ix_symbols_display_symbol'))
        batch_op.drop_index('ix_symbols_display_exchange')

    op.drop_table('symbols')
    op.drop_table('settings')
    op.drop_table('secrets')
    op.drop_table('quotes_cache')
    # ### end Alembic commands ###
