"""news

Revision ID: f2b025ee9893
Revises: 8c2159eb5303
Create Date: 2026-06-28 10:05:44.586908
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f2b025ee9893'
down_revision: str | None = '8c2159eb5303'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_url'), ['url'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_url'))
        batch_op.drop_index(batch_op.f('ix_news_published_at'))

    op.drop_table('news')
    # ### end Alembic commands ###
